.TH LOADNDISDRIVER 8 "September 17, 2006"
.SH NAME
loadndisdriver \- Userspace ndis driver loader for the ndiswrapper
Linux kernel module
.SH SYNOPSIS
.B loadndisdriver
.SH DESCRIPTION
\fBloadndisdriver\fP is a support program for the ndiswrapper Linux
kernel module. The ndiswrapper kernel module uses it to load ndis
drivers that have been installed via the \fBndiswrapper\fP(8)
tool.
.PP
\fBloadndisdriver\fP should not be used directly, only the kernel
module should use it. Therefore, it's options are volatile, and
subject to change during the development of the ndiswrapper kernel
module.
.PP
The \fI/etc/ndiswrapper\fP directory is expected to contain the ndis
files that \fBloadndisdriver\fP requires.
.PP
.SH "SEE ALSO"
\fBndiswrapper\fP(8)
.SH AUTHOR
This manual page was written by Kel Modderman <kelrin@tpg.com.au>,
for the Debian project (but may be used by others).
